### ISSUE TITLE
References represented inside of link block using JSONAPI implementation

### ISSUE THREAD

**Issue by matheusca** [trailblazer/roar#168]
Hi guys,

I've trying create association links using `Roar::JSON::JSONAPI` but I can't reference `represented` method inside of the `has_one` block.

For instance:

``` ruby
class RequesterRepresenter < Roar::Decorator
  include Roar::JSON::JSONAPI

  type :requester

  has_one :residence_address do
    type :address

    link :self do
      # I need way to get requester id here.
      "http://example.com/requester/#{requester.id}/relationships/residence_address"
    end
  end

  property :id
  # ... other properties
end
```

How I described, I would need some way to get `requester.id` inside of `has_one`. Anyway to do it?

**Comment by apotonick** [comment]
Does `represented` work for you? That's the official API!

**Comment by matheusca** [comment]
I can't use `represented` as `requester` inside of `has_one` block, because when I used it, the `represented` is the instance of `residence_address` like example above.

**Comment by apotonick** [comment]
That is correct behaviour. 

The `represented` method refers to the currently rendered object, which is a `residence_address` in your case. 

You can do `represented.requester` if that's what your data model allows. Alternatively, you can pass the requester as a `:user_options` to the block. Representable/Roar does not support accessing parent decorators right now. Let me think about that!

**Comment by apotonick** [comment]
As this might be a common problem in JSON API, we _could_ introduce a `:parent_represented` option, which'd work as follows.

```ruby
link :self do |options|
  options[:parent_represented].id
end
```

**Comment by myabc** [comment]
This issue was moved to trailblazer/roar-jsonapi#14
