### ISSUE TITLE
JSON-API support for :extends/:decorator with has_one

### ISSUE THREAD

**Issue by caseymct** [trailblazer/roar#182]
as per glitter chat:

I have an Event model that `has_one` host, a User. the User model has it's own (quite large) decorator. It would be great to have

```
has_one :host, class: User, decorator: UserDecorator
```

I'd like to avoid doing

```
has_one :host, class: User, populator: ::Representable::FindOrInstantiate do
  # many properties
end
```

and duplicating this in every decorator that has a user.

**Comment by justCxx** [comment]
+1

**Comment by myabc** [comment]
This issue was moved to trailblazer/roar-jsonapi#11
