### ISSUE TITLE
Including Roar::XML modifies the output of Roar::JSON

### ISSUE THREAD

**Issue by ShaneWilton** [trailblazer/roar#186]
Hey @apotonick, thanks for writing this gem, it's really slick!

I'm running into an issue while trying to add XML support to an API. Imagine the following Representer:

```
module PersonRepresenter
  include Roar::JSON

  property :name
end

person = OpenStruct.new(name: "Shane")
person.extend(PersonRepresenter).to_json
=> "{\"name\":\"Shane\"}"
```

However, if I also include `Roar::XML` in that representer, like so:

```
module PersonRepresenter
  include Roar::JSON
  include Roar::XML

  property :name
end

person = OpenStruct.new(name: "Shane")
person.extend(PersonRepresenter).to_json
=> "{\"open_struct\":{\"name\":\"Shane\"}}"
```

I suspect that this is happening because `Representable::XML` calls `representation_wrap = true` on the `self.included` hook.

My question then, is whether this is intended behaviour, or whether I'm doing something incorrectly.

Thanks again!

**Comment by apotonick** [comment]
Including two different engines is not supported! Sorry!

**Comment by ShaneWilton** [comment]
No worries :) Is the "standard" approach in cases like this to have a representer for each Engine, that inherits from the base?

**Comment by apotonick** [comment]
Absolutely yes, especially since you often need to specify different options for XML and JSON.

I can see how this might feel clumsy and we can work on something more sensitive, but this is - unfortunately - not on my priority list right now. Does that still help?

**Comment by ShaneWilton** [comment]
That absolutely makes sense. I just wanted to doublecheck that I'm using
the library as intended. Thanks again!

**Comment by myabc** [comment]
Closing as this looks like this behaviour is intended.
