### ISSUE TITLE
[JSON-API] Rendering an empty relationship

### ISSUE THREAD

**Issue by lasseebert** [trailblazer/roar#189]
I would like to render empty (`nil`) relationships with `JSONAPI` like so:

```
{
  "relationships": {
    "some_relation": { "data": null }
  }
}
```

This is what the jsonapi specification says. See http://jsonapi.org/format/#document-resource-object-linkage

When I use `render_nil: true` in a `has_one` I get

```
undefined method `each' for nil:NilClass
```

It seems like a simple issue to fix inside the `JSON::JSONAPI`. Can anyone confirm that it's not just me doing something stupid? If so I'll be happy to fix it in a pull request :)

**Comment by myabc** [comment]
This issue was moved to trailblazer/roar-jsonapi#8
