### ISSUE TITLE
Using decorators on client-side 

### ISSUE THREAD

**Issue by rguerrettaz** [trailblazer/roar#94]
I'd like to use decorators on both server and client-side and share the representers through a gem... Not seeing a way on the client side to use the decorators to make http requests. 

Is this possible?

**Comment by hilary** [comment]
@apotonick got this working for a different project. (I'm using Virtus models, btw.) The syntax I'm using is:

    class SongDecorator < Roar::Decorator
      include Roar::JSON

      property :title
    end

    class SongClient < SongDecorator
      include Roar::Client
      Roar::HttpVerbs.transport_engine = Roar::Transport::Faraday
    end

    client = SongClient.new(Song.new)
    client.get(...)

works like a charm!

**Comment by apotonick** [comment]
Cool! We should add tests for that kind of usage to Roar, here: https://github.com/apotonick/roar/blob/master/test/client_test.rb

You keen to do that? :wink:

**Comment by hilary** [comment]
Sure :smile:
